### ISSUE TITLE
Failed to run evaluate.py

### ISSUE THREAD

**Issue by Ending2015a** [sThalham/PyraPoseAF#3]
Hello, thank you very much for this amazing project.

I want to reproduce your paper results on LineMOD-Occluded dataset. I have downloaded the dataset and run your annotate_BOP script. But, I have some problems when running the evaluation script:
1. Your paper says (Appendix A) you are using ResNet101 as the backbone model. However, in your `evaluate.py` you use ResNet50 instead. Which one is correct?
https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/bin/evaluate.py#L410-L413
2. When I run the script (using both ResNet50 and ResNet101), it shows the following error:
  ```
  2022-12-08 14:28:47.624960: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at gather_nd_op.cc:47 : INVALID_ARGUMENT: indices[14] = [-1, -1] does not index int$
   param shape [6300,15], node name: cope/filtered_detections/map/while/body/_1/cope/filtered_detections/map/while/GatherNd
  ```
  which is caused by `gather_nd` in the following code:
  https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/layers/filter_detections.py#L280-L284
I think the reason might be your model doesn't detect any thing in the image, so it gets all `-1` from `dummy_fn` in line `233`
https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/layers/filter_detections.py#L220-L240

Could you tell me how to solve these issues?

**Comment by sThalham** [comment]
Hi,

1.) Which branch are you using? given the print with the tensor shape it
looks like you're running "cope_clean". That won't work. The models are
trained with the branch "cope_WACV".
2) If so. Are you sure you're running the code on the gpu? This issue could
be caused running the network on cpu

Best Regards

**Comment by Ending2015a** [comment]
Hello @sThalham,
1. I'm using `cope_WACV` branch (`b0639c1`). It's in `cope/bin/evaluate.py` on `cope_WACV` branch. So, should I use ResNet101 or ResNet50?
2. Thank you, the problem is solved. 
3. But it still doesn't work. The code here:
https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/utils/linemod_eval.py#L605 
shows the error `ValueError: too many values to unpack`, because here returns a list with 5 items.
https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/layers/filter_detections.py#L308

**Comment by Ending2015a** [comment]
@sThalham everything works If I uncomment this block:
https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/utils/linemod_eval.py#L419-L603

The image looks great, but the metric does not match to your paper:
```
ALL: 
mean detection recall:  0.5166694200955905   # paper: 0.532 (table 2)
mean detection precision:  0.6153846153846154
mean pose recall:  0.22523902012751654        # paper: 0.543 (table 1)
mean pose precision:  0.25375701830937314
```


![linemod_pose_0](https://user-images.githubusercontent.com/18180004/206671875-a9bada95-c41d-4695-84e3-6dbecaf6c9f3.png)

**Comment by sThalham** [comment]
Hi @Ending2015a,

great that you got it running!

> Hello @sThalham,
> 
> 1. I'm using `cope_WACV` branch (`b0639c1`). It's in `cope/bin/evaluate.py` on `cope_WACV` branch. So, should I use ResNet101 or ResNet50?
> 2. Thank you, the problem is solved.
> 3. But it still doesn't work. The code here:
>    https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/utils/linemod_eval.py#L605
>    
>    shows the error `ValueError: too many values to unpack`, because here returns a list with 5 items.
>    https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/layers/filter_detections.py#L308


Ad 1.) This parameter is unused if you're loading a trained model
Ad 3.) looks like an error on my end, that might lead to 



> @sThalham everything works If I uncomment this block:
> 
> https://github.com/sThalham/COPE/blob/b0639c1e3078445eb378287f55087ef28e32701b/cope/utils/linemod_eval.py#L419-L603
> 
> The image looks great, but the metric does not match to your paper:
> 
> ```
> ALL: 
> mean detection recall:  0.5166694200955905   # paper: 0.532 (table 2)
> mean detection precision:  0.6153846153846154
> mean pose recall:  0.22523902012751654        # paper: 0.543 (table 1)
> mean pose precision:  0.25375701830937314
> ```
> 
> ![linemod_pose_0](https://user-images.githubusercontent.com/18180004/206671875-a9bada95-c41d-4695-84e3-6dbecaf6c9f3.png)

To clarify, the detection recall and precision is rather of informative value for myself and nonsenical w.r.t. to metric formulation. The pose recall and precision are the ADD/S recall and precision and should correlate with the numbers in Table 3. In the paper.

If you want to reproduce the numbers in Table 1 and 2 you need to evaluate the created cope-lmo.json and cope-lmo.csv with the BOP-toolkit to get the mAP for detection and the AR for pose estimation.
Thank you for bringing that up, that's a good reminder to update and refine the README.md ;)

However, given the low reported detection, you probably commented some important block in linemod_eval.py. I'll look at it later and come back to you.

Best regard

**Comment by sThalham** [comment]
@Ending2015a,

just now I might have realised what was and is going wrong for you.
You want to evaluate on the Linemod-occlusion (LMO) dataset, right? That means you have to specify "occlusion" as dataset parameter and as such, occlusion_eval is used. I'm using the same trained model for linemod and occlusion. 

However, evaluating with the linemod_eval on the occlusion dataset won't give the correct results because the metrics are averaged using 13 as denominator, thus the results will be quite low. 

Let me know if that resolves your issues.

Best regards!

**Comment by Ending2015a** [comment]
@sThalham
Thank you very much for the information. I will try BOP-toolkit later.
And you are right, I just realize that I should use `occlusion_eval` for LMO, but not `linemod_eval`.:sweat_smile:


My problems are all resolved. I will close this issue.
Thanks again for your kind help.

**Comment by sThalham** [comment]
Great!

Thank you for shedding light on things that need to be improved.
